version: 2.1

workflows:
  tagged-release: 
    jobs:
      - releaseUI:
      - deploy:
          requires:
            - releaseUI # only deploy if the releaseUI job has completed
          filters:
            branches:
              only: cibuild # only deploy when on cibuild
jobs:
  releaseUI:
    docker:
     - image: cimg/node:14.20.0-browsers
    
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          name: Build app
          command: | 
            echo "CI Value:" $CI
            TMP_CI=$CI
            CI=""
            npm run build
            CI=$TMP_CI
      - persist_to_workspace:
          root: ~/ui-core
          paths:
            - .
