version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  tagged-release: 
    jobs:
      - releaseUI
      - deploy:
          requires:
            - releaseUI # only deploy if the releaseUI job has completed
          filters:
            branches:
              only: cibuild # only deploy when on cibuild
jobs:
  releaseUI:
    docker:
     - image: cimg/node:14.20.0-browsers
    
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }} 
      - run: npm install 
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
             - node_modules
             - ~/.npm
             - ~/.cache
      - run:
          command: npm run test
          name: Run tests
      - run:
          name: Build app
          command: | 
            echo "CI Value:" $CI
            TMP_CI=$CI
            CI=""
            sudo mkdir ./ui-core
            npm run build
            CI=$TMP_CI
      - persist_to_workspace:
          root: ~/ui-core
          paths:
            - .
  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/ui-core
      - heroku/deploy-via-git:
          force: true