version: 2.1

orbs: 
     docker: circleci/docker@0.5.13
     node: circleci/node@4.7.0
     heroku: circleci/heroku@1.2.6

workflows:
   ui-deploy: 
      jobs:
        - ui-core_build_test

jobs:
  ui-core_build_test:
    working_directory: ~/ui-core 
    docker:
     - image: circleci/python:3.6.8
     - image: circleci/node:latest
       auth: 
          username: vsreddy430
          password: $DOCKERHUB_PASSWORD
    
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }} 
      - run: 
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
             - ./node_modules
     
      - setup_remote_docker
      - run: |
          pwd
          ls
          ls build/*
      - run: |
          if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
          TAG=$CIRCLE_TAG
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          REPONAME = $CIRCLE_PROJECT_REPONAME
          docker build . -t $DOCKER_USER/$REPONAME:$TAG
          #docker tag $REPONAME:latest $DOCKER_USER/$REPONAME:$TAG
          docker push $DOCKER_USER/$REPONAME:$TAG
      
