version: 2.1

orbs: 
     node: circleci/node@4.7.0
     heroku: circleci/heroku@1.2.6

workflows:
   ui-deploy: 
      jobs:
        - ui-core_build_test

jobs:
  ui-core_build_test:
    working_directory: ~/awgment-ui-core 
    docker:
     - image: circleci/python:3.6.8
     - image: circleci/node:latest
       auth: 
          username: vsreddy430
          password: $DOCKERHUB_PASSWORD
    
    steps:
      - checkout
      - restore_cache: 
          keys: 
               - v1-dependencies-{{ checksum "package-lock.json" }}
               - v1-dependencies-
          
      - run: 
           name: Prepare for testing
           command: |
               npm install
      - run:
          name: Run unit-tests
          command: |
               npm run test a
      - setup_remote_docker
      - run: |
          pwd
          ls
          ls build/*
      - run: |
          if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
          TAG=$CIRCLE_TAG
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          REPONAME = $CIRCLE_PROJECT_REPONAME
          docker build . -t $DOCKER_USER/$REPONAME:$TAG
          #docker tag $REPONAME:latest $DOCKER_USER/$REPONAME:$TAG
          docker push $DOCKER_USER/$REPONAME:$TAG
      
