version: 2.1

workflows:
   ui-deploy: 
      jobs:
        - uiBuild

jobs:
  uiBuild:
    docker:
     - image: cimg/node:14.20.0-browsers
    
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }} 
      # - run: npm config set prefix '~/.ui-core'
      # - run: export PATH=~/.ui-core/bin:$PATH
      # - run: npm install -g node-gyp
      # - run: npm install -g node-sass
      # - run: npm install --legacy-peer-deps
      - run: npm install 
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
             - node_modules
             - ~/.npm
             - ~/.cache
      - run:
          command: | 
            echo $CI
            TMP_CI=$CI
            CI=""
            npm run build
            CI=$TMP_CI
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
           if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
            TAG=$CIRCLE_TAG
           echo "$DOCKER_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
           REPONAME=$CIRCLE_PROJECT_REPONAME
           docker build -t $DOCKERHUB_USERNAME/$REPONAME:$TAG .
           docker push $DOCKERHUB_USERNAME/$REPONAME:$TAG
