version: 2.1
workflows:
  ci-build-release: 
    jobs:
      - ciBuild
      - imagePush:
          requires:
            - ciBuild
          context: ossContext
          filters:
            tags:
              only: /^v.*/
            branches:
              only: cibuild
jobs:
  ciBuild:
    docker:
     - image: cimg/node:14.20.0-browsers
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }} 
      - run: npm install 
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
             - node_modules
             - ~/.npm
             - ~/.cache
      - run:
          command: npm run test
          name: Run tests
      - run:
          name: Build app
          command: | 
            echo "CI Value:" $CI
            TMP_CI=$CI
            CI=""
            npm run build
            CI=$TMP_CI
  imagePush:
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
           if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
            TAG=$CIRCLE_TAG

           REPONAME=$DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME
           docker build -t $REPONAME:$TAG . 
           docker push $REPONAME:$TAG